gui:
  theme:
    activeBorderColor:
      - '#fabd2f'  # gruvbox yellow
      - bold
    inactiveBorderColor:
      - '#504945'  # gruvbox bg2
    optionsTextColor:
      - '#83a598'  # gruvbox blue
    selectedLineBgColor:
      - '#3c3836'  # gruvbox bg1
    selectedRangeBgColor:
      - '#504945'  # gruvbox bg2
    cherryPickedCommitBgColor:
      - '#665c54'  # gruvbox bg3
    cherryPickedCommitFgColor:
      - '#8ec07c'  # gruvbox aqua
    unstagedChangesColor:
      - '#fb4934'  # gruvbox red
    defaultFgColor:
      - '#ebdbb2'  # gruvbox fg1
    searchingActiveBorderColor:
      - '#fe8019'  # gruvbox orange
      - bold
